language: python
python: "3.4"
env:
  global:
    - SECRET_KEY="travis"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - coverage run manage.py test
after_success:
  - coveralls
