language: python
python: "3.4"
env:
  global:
    - DJANGO="Django<1.9"
    - SECRET_KEY="travis"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - pip install $DJANGO --use-mirrors
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - coverage run manage.py test
after_success:
  - coveralls
